# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risposta',
            name='risposta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domanda',
            name='categoria',
            field=models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='risposta',
            name='anno',
            field=models.IntegerField(choices=[(2016, 2016)], default=2016),
        ),
    ]
