# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande', '0002_auto_20160822_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='domanda',
            name='fetta',
            field=models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domanda',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
    ]
